# python ./tagset_gen.py -c /home/cc/praxi/demos/ic2e_demo/demo_changesets/data4_sampled -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/iter_init
# mkdir results
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/sampled0 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/test_sampled0 -o results -i iter_model.vw -l
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/sampled3 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/test_sampled3 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/sampled6 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/test_sampled6 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/sampled9 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/test_sampled9 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/sampled12 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/test_sampled12 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/sampled15 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/test_sampled15 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/sampled18 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/test_sampled18 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/sampled21 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/test_sampled21 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/sampled24 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/test_sampled24 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/sampled27 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/test_sampled27 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/sampled30 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/test_sampled30 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/sampled33 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/test_sampled33 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/sampled36 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/test_sampled36 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/sampled39 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/test_sampled39 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/sampled42 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/test_sampled42 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/sampled45 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/iter_init_batched/test_sampled45 -o results -p iter_model.p
