# python /home/cc/praxi/demos/ic2e_demo/tagset_gen.py -c /home/cc/praxi/demos/ic2e_demo/demo_changesets/data4_sampled -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled
# python /home/cc/praxi/demos/ic2e_demo/tagset_gen.py -c /home/cc/praxi/demos/ic2e_demo/demo_changesets/data4_sampled_one_batch -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch
# python /home/cc/praxi/demos/ic2e_demo/tagset_gen.py -c /home/cc/praxi/demos/ic2e_demo/demo_changesets/data4_sampled_one_ver -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver

# mkdir results
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched/sampled0 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched/test_sampled0 -o results -i iter_model.vw -l
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched/sampled1 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched/test_sampled1 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched/sampled2 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched/test_sampled2 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched/sampled3 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched/test_sampled3 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched/sampled4 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched/test_sampled4 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched/sampled5 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched/test_sampled5 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched/sampled6 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched/test_sampled6 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched/sampled7 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched/test_sampled7 -o results -p iter_model.p


# mkdir results
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/sampled0 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/test_sampled0 -o results -i iter_model.vw -l
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/sampled3 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/test_sampled3 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/sampled6 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/test_sampled6 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/sampled9 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/test_sampled9 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/sampled12 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/test_sampled12 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/sampled15 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/test_sampled15 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/sampled18 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/test_sampled18 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/sampled21 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/test_sampled21 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/sampled24 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/test_sampled24 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/sampled27 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/test_sampled27 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/sampled30 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/test_sampled30 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/sampled33 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/test_sampled33 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/sampled36 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/test_sampled36 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/sampled39 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/test_sampled39 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/sampled42 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/test_sampled42 -o results -p iter_model.p
python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/sampled45 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_batch_batched_3/test_sampled45 -o results -p iter_model.p


# # mkdir results
# # python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/sampled0 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/test_sampled0 -o results -i iter_model.vw -l
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/sampled3 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/test_sampled3 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/sampled6 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/test_sampled6 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/sampled9 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/test_sampled9 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/sampled12 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/test_sampled12 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/sampled15 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/test_sampled15 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/sampled18 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/test_sampled18 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/sampled21 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/test_sampled21 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/sampled24 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/test_sampled24 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/sampled27 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/test_sampled27 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/sampled30 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/test_sampled30 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/sampled33 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/test_sampled33 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/sampled36 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/test_sampled36 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/sampled39 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/test_sampled39 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/sampled42 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/test_sampled42 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/sampled45 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_batched_3/test_sampled45 -o results -p iter_model.p


# # mkdir results
# # python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/sampled0 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/test_sampled0 -o results -i iter_model.vw -l
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/sampled3 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/test_sampled3 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/sampled6 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/test_sampled6 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/sampled9 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/test_sampled9 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/sampled12 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/test_sampled12 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/sampled15 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/test_sampled15 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/sampled18 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/test_sampled18 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/sampled21 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/test_sampled21 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/sampled24 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/test_sampled24 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/sampled27 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/test_sampled27 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/sampled30 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/test_sampled30 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/sampled33 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/test_sampled33 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/sampled36 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/test_sampled36 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/sampled39 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/test_sampled39 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/sampled42 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/test_sampled42 -o results -p iter_model.p
# python /home/cc/praxi/demos/ic2e_demo/demo_main.py -t /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/sampled45 -s /home/cc/praxi/demos/ic2e_demo/demo_tagsets/data4_sampled_one_ver_batched/test_sampled45 -o results -p iter_model.p
